package apacheloganalyzer;

import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


// Java program to calculate MD5 hash value
public class Test {
    private static final Charset UTF_8 = StandardCharsets.UTF_8;
    private static final String OUTPUT_FORMAT = "%-20s:%s";
	public static String getMd5(String input)
	{
		try {
                        
                        //byte[] bytesOfMessage = input.getBytes("UTF-8");
			// Static getInstance method is called with hashing MD5
			MessageDigest md = MessageDigest.getInstance("MD5");

			// digest() method is called to calculate message digest
			// of an input digest() return array of byte
			byte[] messageDigest = md.digest(input.getBytes(UTF_8));
                        
                        //md.update(messageDigest);
                        //messageDigest = md.digest();
			// Convert byte array into signum representation
			BigInteger no = new BigInteger(1, messageDigest);

			// Convert message digest into hex value
			String hashtext = no.toString(16);
			while (hashtext.length() < 32) {
				hashtext = "0" + hashtext;
			}
                        
			//return bytesToHex(messageDigest);
                        return hashtext;
		} catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		} 
	}
        
         private static String bytesToHex(byte[] bytes) {
            StringBuilder sb = new StringBuilder();
            for (byte b : bytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        }

	// Driver code
	public static void main(String args[]) throws NoSuchAlgorithmException
	{
		String s = "2fvmer3qbk7f3jnqneg58bu2qvxkmw57pec71200603038";
            //String s = "Hello MD5";
		//System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
                System.out.println("Your HashCode Generated by MD5: " + getMd5(s));
	}
}
